spring.application.name=JobTracker

# Database Connection
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Gemini AI Autoconfiguration via Starter
gemini.api.key=${GEMINI_API_KEY}


# JWT Configuration
# This is a base64 encoded secret key (min 256 bits). DO NOT use this exact key in production!
jwt.secret=${JWT_SECRET}

# Token expiration time in milliseconds (86400000 = 24 hours)
jwt.expiration=${JWT_EXPIRATION_MS:86400000}

app.frontend.url=${FRONTEND_URL}
